qri-io/dataset

- dsfs/data.go
- dsfs/data_test.go
- dsfs/dataset.go
- dsfs/testdata/cities.csv
- dsfs/testdata/cities.json
- dsfs/testdata/movies.csv
- dsfs/testdata/movies.json
- dsfs/testdata_test.go
- dsio/buffer.go
- dsio/buffer_test.go
- dsio/csv.go
- dsio/csv_test.go
- dsio/dsio.go
- dsio/json_writer.go
- dsio/rows.go
- dsio/rows_test.go
- dsio/teststore_test.go
- metadata.go
- metadata_test.go
- validate/data.go
- validate/data_test.go
- validate/dataset.go
- validate/structure.go
- validate/validate.go
- validate/validate_test.go
- validate_test.go
moving stuff around to make more sense
> package refactor

- validate/csv.go
- validate/csv_test.go
- validate/data.go
- validate/data_test.go
- validate/testdata.go
includes
- checking whether all rows have the same number of columns
- checking whether column names are sql compliant
- checking that column names are unique
> test(csv validation): added tests to ensure well-formed csvs and valid column names

- dataset.go
- metadata.go
- metadata_test.go
this'll let us know how frequently to re-check url-based datasets
> feat(dataset.Dataset): add AccrualPeriodicity field

- dsfs/dataset.go
- dsfs/dataset_test.go
> test(dsfs.SaveDataset): add empty Dataset test cases

- dsfs/dataset.go
- dsfs/dataset_test.go
need to check calls to CreateDataset that don't provide a private key for signing
> feat(dsfs.CreateDataset): added private key check

- datatypes/datatype.go
- datatypes/datatype_test.go
Add:
- IsInteger
- IsBoolean
- IsFloat
- IsDate
- IsJSON
Add benchmarks to:
- IsInteger
- Parse
- ParseDatatype
> feat(benchmarks): benchmark tests for datatype package

- compare.go
- compare_test.go
- dataset.go
- dataset_test.go
- dsfs/dataset.go
- dsfs/dataset_test.go
- dsfs/package.go
- dsfs/testdata/cities.json
- kind.go
- kind_test.go
- testdata/visconfigs/invalidJSON.json
- testdata/visconfigs/visconfig1.json
- testdata/visconfigs/visconfig2.json
- testdata/visconfigs/visconfig3.json
- vis_config.go
- vis_config_test.go
> Add initial Viz field to dataset.Dataset

- transform.go
- transform_test.go
> feat(transform): fix bug in IsEmpty

- dsfs/dataset.go
- dsfs/dataset_test.go
- dsfs/testdata/cities.json
- dsfs/testdata/cities_no_commit_title.json
> fix: updates with no changes should fail

- vals/coding_test.go
- vals/value.go
- vals/value_test.go
> test(vals.value): increase test coverage

- dsfs/dataset.go
- dsfs/dataset_test.go
> feat(timestamp): dsfs.Timestamp now an exported function

- .circleci/config.yml
- dsfs/dataset.go
Changing dataset imports to reflect that
> refactor(dsdiff): datasetDiffer packet was renamed to dsdiff

- dsfs/transform.go
- dsfs/transform_test.go
- dsfs/viz.go
- dsfs/viz_test.go
we need these higher up the stack, so let's get 'em in & tested.
closes #144
> convenince funcs for loading script files

- dsfs/dataset.go
- dsfs/dataset_test.go
- dsfs/transform_test.go
- dsfs/viz_test.go
- subset/subset_test.go
sometimes we need to tell the safeguards against "not-meaningful commits" to ease up. This adds such a feature
> feat(dsfs.CreateDataset): add force flag to force an update without changes

- dsio/xslx.go
looks like our excelize dep made a breaking API change, this brings us up to speed
> fix(xlsx): update broken excelize API dep

- dsio/streams_test.go
I think we need more tests for csv reading & writing generally, this adds a quick sanity test that our code can interpret header rows correctly with csv data.
> test(dsio): add sanity test for csv-to-csv dsio.Copy

- dsio/replacecr/replace_cr.go
ran into this issue while working on a dataset. I don't have time to write a test, but it's better code than before
> handle "edge" case of reader p slice overflow

- dataset.go
- dsfs/body.go
- dsfs/body_test.go
- dsfs/commit_msg.go
- dsfs/commit_msg_test.go
- dsfs/dataset.go
- dsfs/dataset_test.go
- dsfs/meta.go
- dsfs/meta_test.go
- dsfs/structure.go
- dsfs/structure_test.go
- dsfs/testdata_test.go
- dsfs/transform.go
- dsfs/transform_test.go
- dsfs/viz.go
- dsfs/viz_test.go
- dsutil/dsutil.go
- dsutil/dsutil_test.go
- dsutil/zip.go
- dsutil/zip_test.go
- go.mod
- go.sum
- subset/subset.go
- subset/subset_test.go
- transform.go
- viz.go
> refactor(context): add context plumbing for qfs

- dsio/json.go
- dsio/json_test.go
- go.mod
- go.sum
Also adds tests to illustrate previous bug
> fix(NewJSONPrettyWriter): now writer correctly writes object values when indenting

- transform.go
need this for cursory transform FSI support
> feat(transform): add InlineScript method, matching readme

- detect/determineFields_test.go
- go.mod
- go.sum
- readme.go
- structure.go
- transform.go
- validate/data.go
- validate/data_test.go
Depends on landing the JSON Schema work and alligning apis and dependencies before merge.
> refactor(jsonschema): updating jsonschema, adding streaming validation

- dstest/dstest.go
important for qfs refactoring work
> refactor(dsfs): add leading slash to dstest body filepath

- dstest/template.go
simple template function to make gropuing hashes in tests easier
> feat(dstest): add Template function

- dstest/golden.go
- meta.go
- meta_test.go
one fix & a little bit of feedback from https://github.com/qri-io/qri/pull/1579
> fix meta component serialize, add dstest Golden file Compare-And-Update convenience function

- compression/compression.go
- detect/detect_test.go
- dsio/cbor_test.go
- dsio/csv_test.go
- dsio/json_test.go
I incorrectly thought it was 'zstd'
> fix(compression): fix zstandard file extension: 'zst'

- dsstats/stats.go
- dsstats/stats_test.go
Turns keys in string frequency stats that are longer than 80 characters from the full value being into a string of the first 80 characters truncated + `... X chars`. Does this on `Close`, so it only affects the final output.
This prevents string stat frequencies from blowing up preview sizes. The result here is admittedly a little controversial, as we need to cover a specific edge case: truncating strings can cause keys to collide if the only differences between two frequency values occurs after the first 80 characters. This is helped somewhat by templating in the length of the string, but doesn't handle the case where two strings of the same length differ only after the first 80 characters. For that reason I've added the index of the bucket in paranthesis after the character count. Given …
> feat(dsstats): truncate string frequency labels when values exceed 80 chars
