dsfs/data.go, dsfs/data_test.go, dsio/cdxj.go, dsio/cdxj_test.go, dsio/csv.go, dsio/csv_test.go, dsio/dsio.go, dsio/json.go, dsio/structured_buffer.go, dsio/structured_buffer_test.go, dsio/structured_row_buffer.go, dsio/structured_row_buffer_test.go, dsio/testdata/movies.json, dsio/testdata/movies_sorted_movie_title.csv, validate/data.go
this commit extracts the basics of RowBuffer from the dataset_sql package
into the dsio package, allowing us to do things like sort data by fields
without having to move through the sql package.
BREAKING CHANGES:
* dsio.Buffer is now dsio.StructuredBuffer (for clarity)
* dsio.CSVWriter now writes a header line if the structure.FormatConfig
indicates HeaderRow = true
=> feat(dsio.StructuredRowBuffer): added StructuredRowBuffer

commit.go, dataset.go, dataset_test.go, dsfs/commit_msg.go, dsfs/dataset.go, dsfs/dataset_test.go, dsfs/package.go, dsfs/structure.go, dsfs/transform.go, dsfs/transform_test.go, dsgraph/graph.go, kind.go, structure.go, testdata_test.go, transform.go
In what feels like a final piece of the white paper puzzle,
abstract interoperability comparison will now be done with
abstract datasets instead of raw abstract structures.
Datasets now keep an Abstract field, which is the result of
calling Abstract on the dataset itself.
Abstract datasets are currently just their structure, abstracted,
and a dataset kind identifier. This makes it a valid dataset,
gives us the capacity to break hashes on version changes (for all
the mistakes the spec undoubtly contains).
The real win here comes in generating abstract transforms from
concrete transforms, which is now just a process of calling
Abstract on the resources, and means that there's no need for
a structural difference between abstract & concrete transforms.
=> refactor(dataset.Abstract): replace AbstractStructure with Abstract

dsfs/dataset.go, dsfs/dataset_test.go, dsfs/transform_test.go, structure.go, structure_test.go, testdata/structures/airport-codes.json, testdata_test.go
dataset.Structure now has a field to store the number of validation errors in a given dataset. `dsfs.CreateDataset` now fills this out at time of dataset creation automatically.
closes #47
=> feat(dataset.Structure): add ErrCount field to structure

commit.go, commit_test.go, structure.go, structure_test.go, transform.go, transform_test.go, vis_config.go, vis_config_test.go
closes #67 / see for more details
=> refactor: expose `MarshalJSONObject()` methods for dataset subcomponents

dsfs/commit_msg.go, dsfs/dataset.go, dsfs/meta.go, dsfs/structure.go, dsfs/transform.go, dsfs/vis_config.go
Deref methods were using their exported Load counterparts for example `dsfs.DerefDatasetMetadata` was calling `dsfs.LoadMetadata`, which was causing `/meta.json` to be appended to valid hashes of the meta file. In this case hash of the metadata file was `QmFoo...`, but now `LoadMetadata` was adding `/meta.json` when what we want is just `QmFoo...`. 
So I've added a set of unexported methods that deref can use, sharing this code with their exported `Load` counterparts.
=> fix(dsfs): added set of unexported load methods

compare.go, compare_test.go, dataset_test.go, dsfs/dataset_test.go, dsfs/testdata/complete.json, dsfs/vis_config_test.go, testdata/visconfigs/visconfig1.json, testdata/visconfigs/visconfig2.json, testdata/visconfigs/visconfig3.json, vis_config.go, vis_config_test.go
Following the pattern established by other structures in Dataset (Structure, Meta, etc), the `Kind` field has been changed to `Qri`
closes #65
=> refactor(visConfig): changed VisConfig field `Kind` to `Qri` 

commit.go, commit_test.go, dataset.go, dataset_test.go, meta.go, meta_test.go, structure.go, structure_test.go, transform.go, transform_test.go, vis_config.go, vis_config_test.go
should be used with caution and only as a last resort. specifically used in the qri core function Save
Closes #85
=> feat(SetPath): the SetPath function allows outside packages to change the path

dsfs/dataset.go, dsfs/dataset_test.go, dsfs/testdata/cities/expect.dataset.json, dsfs/testdata/complete/expect.dataset.json, dsfs/testdata/craigslist/data.json, dsfs/testdata/craigslist/expect.dataset.json, dsio/json.go, dsio/json_test.go, dsio/testdata/craigslist.json, dstest/dstest.go
This PR deals with two major bugs found while working with JSON-formatted data:
dsio.JSONReader wasn't properly observing escaped quote characters, causing it to do very odd things when `\"` was encounteed in a JSON document, it now does. This was throwing off the craigslist entries count. fixed.
Also, there was an off-by-one error in dsfs.prepareDataset for entry counting that was causing all dataset entry counts to be one more than what they actually wer. now also fixed.
Also, I'd stupidly left a whole series of tests commented-out in the dsio package. Those are back now.
=>  fix(dsio,dsfs): fix bugs in entry counts, json reader string error

dsfs/dataset.go, dsfs/dataset_test.go, dsfs/testdata/cities/expect.dataset.json, dsfs/testdata/craigslist/expect.dataset.json
Dataset Abstractions are starting to lose their relevance in the general qri architecture. For now I'm removing them from being written. They're wasted space until we have a good reason for writing them.
=> refactor(dsfs.CreateDataset): don't create dataset Abstract on save

dsfs/dataset_test.go, dsio/cbor_test.go, dsio/entry_buffer_test.go, dsio/entry_test.go, dsio/json_test.go, dstest/dstest.go, dstest/dstest_test.go, validate/data_test.go
also, removed the need to provide a *testing.T to dstest funcs, paving the way for pulling these sorts of funcs up & out into a library that allows standard unix file format interop with qri.
=> test(dstest): added LoadTestCases func to load a dir of test cases

generate/generate.go, generate/generate_test.go
The generate package now inspects the jsonschema it owns, but only to determine if it's an array or
object. It also implements dsio.EntryReader, returning an entry with random data on each call.
Resolves #101.
=> refactor(generate): update generate package so it creates random entries

dsio/README.md, dsio/cbor_test.go, dsio/csv_test.go, dsio/json_test.go, generate/generate_test.go
Benchmarks for multiple EntryWriter implementations. Add current benchmark numbers to a README file. Also fix a test broken by 6a7bffac6e. Resolves #102.
=> test(dsio): benchmark EntryWriter usage for JSON, CBOR, and CSV

dsio/README.md, dsio/fuzz.go, generate/generate.go, generate/generate_test.go, use_generate/main.go
Add a small binary to generate example json entries. Add an entry-point that go-fuzz can use to
perform fuzz testing. Add documentation on how to run fuzz testing.
This is a partial fix to #103, but doesn't fully solve it yet because the readers do not handle errors well enough for fuzz testing to work properly.
=> feat(dsio): Generate example entries, fuzz testing, documentation

dsio/README.md, dsio/entry_test.go, dsio/json.go, dsio/json_test.go
Rewrite JSONReader to use bufio.Reader instead of bufio.Scanner. Improve error handling (with test cases), performance (x2 speedup if memory usage remains), prevent crashes if memory usage is reduced.
Previous implementation of the JSONReader did not handle multiple types of malformed JSON. See the test "TestJSONReaderErrors"; all test cases with error messages used to be parsed without an error being detected.
The previous implementation of JSONReader used a huge buffer size (256KB) in order to handle large tokens. If this new version uses the same buffer size, it improves performance by 2x. The reason is that the old code would scan strings byte by byte, and then reparse using json.Unmarshal. This new version only scans one, building elements as it goes. Likely, the entire runtime of …
=> feat(dsio.JSONReader): rewrite JSONReader for better errors and performance

.circleci/config.yml, dsio/entry.go, dsio/json.go, dsio/json_test.go, validate/data.go
Found a weird edge case while adding a large json file. validate uses dsio.JSONReader to validate json data, which was failing if while reading object/array and r.reader.Buffered() doesn't contain a valid token.
From what I can tell, it seems this only occurs in rare circumstances where the desired token lines up with the end of the current buffer, which zeros out the buffer, and on next read causes the tokenization process to fail.
@dustmop I managed a possibly-terrible fix by checking the length of `r.reader.Buffered()` at the top of each iteration of an object or array read. This might be better placed, and I'd be happy to adjust this PR based on what you think.
=> fix(dsio.JSONReader): handle edge case of object/array reading empty buffer

.circleci/config.yml, commit.go, commit_test.go, dataset.go, dataset_test.go, structure.go, structure_test.go, transform.go, transform_test.go
To represent plain-old-data, meant for serialization, use the Pod suffix instead of Coding.
=> refactor(CodingPattern): change Coding to Pod

dataset.go
To get the new render command to work properly, we gotta add a few fields to DatasetPod, while here I roughed in `DataBytes`, which we're going to need for this whole cbor/protobuf thing to work.
Slowly but surely `DatasetPod` is starting to eat into the duties of `repo.DatasetRef`, which I think is a good thing. Long term I'd like to bring these two closer together, with `repo.DatasetRef` wrapping `DatasetPod`, providing methods for Dataset/Repo interaction & name resolution.
=> feat(DatasetPod): add convenience fields to DSP

detect/json.go, detect/json_test.go, dsfs/dataset.go
I've been meaning to do this for a while, this change should make working with large files faster by splitting up dataset prep work into piped read/writers. Unfortunately, `CreateDataset` still needs to accumulate a full copy of the data at least once to calculate the checksum hash, but if we can find a way to do rolling SHA2_256 checksums, this requirement could be removed. In the future I'd also like to refactor `prepareDataset` further, ideally merging the whole func into WriteDataset, but that'll have to wait for another day.
This PR also includes a fix & test for our naive `detect.JSONSchema` func, which was causing errors in userland.
=> perf(dsfs.CreateDataset): parallelize ds prep with io.MultiWriter

.circleci/config.yml, detect/cbor.go, detect/detect.go, detect/determineFields.go, detect/json.go, detect/json_test.go, dsfs/dataset.go, dsio/tracked_reader.go, dsio/tracked_reader_test.go, dstest/dstest.go, dstest/dstest_test.go, dsutil/dataset_yaml.go, dsutil/dataset_yaml_test.go, structure.go, validate/dataset.go, validate/dataset_test.go
I'm hoping we can enforce a new rule around qri:
> _any function that accepts an io.Reader and may only read part of the reader must return the number of bytes read_
io.Reader's `Read` method returns the number of bytes read and an error. This is simply echoing that pattern. In many cases the caller of such a function will ignore this bytes-read count, but by keeping this in the return signature it both signals to the caller that "hey, this thing might do funny stuff to your reader", *and* forces the author of the function to track what they're doing to the reader. We get all of this without introducing any novel conventions, just requiring that io.Reader's return signature be honored.
With that in mind, I've started with an update to `detect.FromReader`, and added a new TrackedReader, …
=> Detect track bytes read

data_format_config.go, data_format_config_test.go, dsfs/dataset_test.go, dsfs/transform_test.go, dsio/csv.go, dsio/csv_test.go, structure.go
When working with CSV data that was close-but-not-quite-perfect for parsing, I've been missing being able to set these csv.Reader options. I've adjusted dsio.CSVReader & dsio.CSVWriter to leverage these & configure the underlying CSV reader/writer.
=> feat(CSVOptions): added LazyQuotes, Separator, VariadicFields options

meta.go, meta_test.go
We need a consistent way to set metadata. At some point we should also add a get method, but, you know, time.
=> feat(Meta.Set): add Set method to meta

dsio/dsio.go, dsio/json.go, dsio/streams.go
ConvertFormat takes an io.Reader of bytes in some parsable format, and converts
it into an EntryBuffer of any other desired format.
=> feat(dsio): ConvertFormat utility function

dsio/dsio.go, dsio/json.go, dsio/streams.go
We were using a variable ErrEOF to check against errors, but this will never return true. We need to use io.EOF to compare instead.
=> fix(dsio.ErrEOF): should be replaced with io.EOF

compare.go, compare_test.go, dataset.go, dataset_test.go, dsfs/data.go, dsfs/dataset.go, dsfs/dataset_test.go, dsfs/testdata/cities/expect.dataset.json, dsfs/testdata/complete/expect.dataset.json, dsfs/testdata/craigslist/expect.dataset.json, testdata/datasets/hours.json, testdata_test.go, transform_test.go
After a bunch of discussion, we've decided to rename "Data" to "Body", our logic is outlined here: https://github.com/qri-io/qri/issues/422. Basically it's just a rename, but it renames a required field. This'll break all sorts of stuff, but considering we're still _very_ early days, I'd rather get it merged now.
To me this dataset-as-html-page metaphor is worth a breaking change, so let's make one.
BREAKING CHANGE: dataset.DataPath is renamed to dataset.BodyPath.
=> feat(dataset.Body): rename Data fields to Body

.circleci/config.yml, dstest/dstest.go
Our unit tests currently spend a lot of time re-reading and re-parsing test
files. Though these are quick individually, they add up to a significant
total of tests' runtimes, especially the craigslist/*.dataset.json files, which
are over 1MB and take about 1 second to parse. By caching these reads and
parses, and returning copies on future calls, we speed up tests by about 35%.
Some performance numbers follow.
Before this change:
```
Run 0
ok      github.com/qri-io/qri/api      25.587s
ok      github.com/qri-io/qri/cmd      84.258s
ok      github.com/qri-io/qri/config   48.832s
ok      github.com/qri-io/qri/lib      90.485s
ok      github.com/qri-io/qri/p2p      54.261s
Run 1
ok      github.com/qri-io/qri/api      30.159s
ok      github.com/qri-io/qri/cmd      79.327s
ok …
```
=> fix(dstest): Cache the reading of TestCases, speeding up unit tests

data_format_config.go, data_format_config_test.go, detect/detect_test.go, detect/determineFields.go, detect/determineFields_test.go, detect/testdata/daily_wind_2011.structure.json, detect/testdata/hours-with-header.structure.json, detect/testdata/hours.structure.json, detect/testdata/spelling.structure.json, dsfs/dataset.go, dsio/csv_test.go
Found & fixed a few bugs in csv.FormatConfig.Map(). Dope. Also realized that detect needs
to do more work when generating csv.FormatConfig.
A bunch of our parsing errors come from not having csv.Reader engage the LazyQuotes option,
and a few others come from not properly setting variadicFields. For now I've switched on
lazyQuotes for everything which will produce a general slowdown when working with csv,
but will mean _many_ more gross csv files will be parsable by Qri. Long term I think we
should solve the LazyQuotes slowness with two things: a default-convert-to-cbor, and a full
csv file scan that properly infers the need for lazyQuotes.
closes #140
=> fix(csv): inferred csv structures use lazyQuotes by default, set VariadicFields

dsfs/dataset.go, dsio/csv.go
providing an empty slice to a CSV reader with `headerRow: true` would cause infinite loops. Also, don't pass mutexes by reference.
=> fix(dsio.CSVReader,dsfs.CreateDataset): fix mutex pass-by-ref, csv read corner case

dsio/README.md, dsio/cbor.go, dsio/cbor_test.go, dsio/streams_test.go
Rewrite CBOR reader so that it avoids buffering tokens. Instead, output parsed elements as they are read off the input reader. Decode CBOR bytes on our own, instead of relying on another library (which is what required buffering).
Performance is about 3x better. Before:
```
> go test ./dsio/. -bench=.
BenchmarkCBORWriterArrays-2    	    3000	    441960 ns/op
BenchmarkCBORWriterObjects-2   	    3000	    617959 ns/op
BenchmarkCBORReader-2          	     200	   6453132 ns/op
BenchmarkCSVWriterArrays-2     	    1000	   1547526 ns/op
BenchmarkCSVWriterObjects-2    	    1000	   1970756 ns/op
BenchmarkCSVReader-2           	     500	   2300161 ns/op
BenchmarkJSONWriterArrays-2    	    1000	   1890182 ns/op
BenchmarkJSONWriterObjects-2   	     500	   2021165 ns/op
BenchmarkJSONReader-2 …
```
=> refactor(cbor): Rewrite of CBOR reader. Faster and simpler.

compare.go, compare_test.go, detect/determineFields.go, dsfs/dataset.go, dsfs/dataset_test.go, dsfs/testdata/all_fields/expect.dataset.json, dsfs/testdata/cities/expect.dataset.json, dsfs/testdata/craigslist/expect.dataset.json, dsio/csv.go, dsio/csv_test.go, dsio/replacecr/replace_cr.go, dsio/replacecr/replace_cr_test.go, dstest/dstest_test.go, structure.go, structure_test.go, subset/subset_test.go, testdata/structures/hours.json, testdata_test.go
This all secretly about tabular data, and properly detecting when we're dealing with it. Because JSON-schema is more about validation & description then definite requirements, we need another heuristic for checking if a dataset is "a table". 
The better way to phrase this in my opinion is to check the maximum number of dimensions a dataset contains:
| depth | example |
|-------|----------|
| 0 | `"hello"` |
| 1 | `["hello", "friend"]` |
| 2 | `[["hello", "friend"], ["how","are","you"]]` | 
| 3 | `[[  "hello",{ "friend" : true }], ["how,"are","you" ]]` |
Note in that last example there's only one place where the nesting level is 3 closures deep, but the depth is still 3.
We could have called this "maxDepth", but that implies there's a "minDepth", which doesn't make any sense (it would …
=> feat(structure.Depth): add depth parameter to detect tabular data

dsfs/dataset.go, dsfs/dataset_test.go, dsfs/testdata/cities_no_commit_title/input.dataset.json, dsfs/transform_test.go, dsfs/viz_test.go, subset/subset_test.go
closes #164 
This fixes a bug in Qri, where you can't do a dry-run on a dataset that has a previous version.
This also changes some of how our commit message is generated. Removed references to adding a commit title from qri, and put it all in `generateCommitMsg`
Also made a note where we can perhaps use another wrapper function `generateCommit` that takes a dataset and a previous dataset, and runs `generateCommitMsg`, cleans the title and message, signs the commit, etc.
Also pushes the test coverage back up to 80% what whaaaat
=> refactor(CreateDataset): first step toward CreateDataset as a write only (to the store) function

dsfs/dataset.go
If a user tries to save a file consisting of line-delimited json structures, prepareDataset has the possibility of deadlocking. The reason is that `setErrCount` and `setDepthAndEntryCount` use EntryReaders, and will only consume the first json object. However `setChecksumAndStats` uses a normal byte based file reader, so it will attempt to read the entire file. The io.MultiWriter that is supplying these three goroutines will be writing data to each of them, which will fill up the I/O buffers for `setErrCount` and `setDepthAndEntryCount`, eventually causing `Write` within the
io.MultiWriter to block.
Fix this by closing the file handles in `setErrCount` and `setDepthAndEntryCount` when they are done. A future improvement would be detecting this situation somewhere and returning an error …
=> fix(save): Fix deadlock when saving invalid file

dsfs/dataset.go
we can't do a check for meaningful changes until we have a proper differ in place. Walking back this check until we have such a thing.
=> fix(dsfs.CreateDataset): remove 'no meaninful changes' check

dsfs/dataset.go, dsfs/dataset_test.go, dsfs/package.go, dsfs/package_test.go
In order to load the dataset from the store, we need to append the `/dataset.json` suffix to the path. However, we were incorrectly adding that same path (with the extension) to the dataset as the path.
Created another var `pathWithExt` that we use to get the dataset from the store.
closes qri-io/qri#700
=> fix(loadDatasetRefs): add correct path to dataset

dsfs/dataset.go, dsfs/dataset_test.go, dsfs/transform_test.go, dsfs/viz_test.go, subset/subset_test.go, viz.go
Adds `shouldRender` flag to `CreateDataset` and `prepareDataset`. If `true`, `shouldRender` indicates we should render the template and store it as part of the dataset package.
Adds `OpenRenderedFile` function to generate a byte stream of the rendered file
=> refactor(CreateDataset): add `shouldRender` flag

dsviz/render.go, dsviz/testdata/custom/rendered.html, dsviz/testdata/custom/template.html
having "paginated" access to template functions is important for fixed record sampling. While here I've taken the liberty of renaming `getBody` to `allBodyEntries` to clearly label for template readers that 'hey, this is going to read all the body'. With these in place we can remove the all,limit, and offset parameters from `qri render`.
They'd be used like this in template funcs:
```html
// grab the first 10 rows, printing all data in paragraph tags
{{ range bodyEntries 0 10 }} 
<p>{{ . }}</p>
{{ end }}
// print the whole body as JSON:
<script>
window.data = {{ allBodyEntries }}
</script>
```
@dustmop b/c this is a public-facing API with offset & limit params, I've put them in offset-then-limit order, as we've discussed earlier. This makes it a bit confusing for us codebase maintainers, …
=> feat(dsviz): add bodyEntries and allBodyEntries template funcs

dsviz/doc.go, dsviz/render.go
this defines the base API for viz templating. qri makes a few special partials available that we can document by copy-pasting this & adding to
=> doc(dsviz): add outline doc.go for dsviz

dsfs/dataset.go, dsfs/dataset_test.go, dsfs/testdata/strict_fail/body.csv, dsfs/testdata/strict_fail/input.dataset.json, structure.go, structure_test.go, validate/data.go
builds on #190.
Add a field to the structure component the _requires_ valid data in order to make a change. 
In the future I'd like to investigate adding a more nuanced set of validation logic to the schemas themselves that would allow progressive enhancement of datasets (eg: "this column MUST pass validation"), but even that would be working toward being able to set `strict: true`
In later enhancements we can check for strict: true in packages like `dsio` to facilitate memory allocation speedups. User interfaces can show some sort of check or seal declaring the dataset as "clean data". Finally, we should be able to do cool things when two datasets are strict, thanks to the fact that we know the data won't contain any surprises
=> structure.strict: true requires validation to pass 

.circleci/config.yml, commit.go, commit_test.go, dataset.go, dataset_test.go, go.mod, go.sum, meta.go, meta_test.go, structure.go, structure_test.go, transform.go, transform_test.go, viz.go, viz_test.go
we've defined a _derived_ value to be any field that is set by qri at runtime. Dropping derived values is an important step for comparing a saved dataset to an input dataset.
=> feat(DropDerived): add methods for dropping derived values

dsio/json.go, dsio/json_test.go, go.mod
ran into this issue from funky output of a QGIS conversion. Turns out escaping forward slashes are _allowed_, but not required in JSON.
I've made a note in code on how this solution can be improved, but I think this'll work just fine for a long while
=> fix(dsio): don't fail on escaped forward slashes

dsio/json.go, dsio/json_test.go, dsviz/render.go
this is breaking the differ otherwise, which expects int64 values.
=> fix(dsio): json decoder emits int64 instead of int

vals/coding_test.go
Change to coding/ConvertDecoded tests to account for the new type conversions. Fixes https://github.com/qri-io/dataset/issues/207
=> test(vals): expand tests for ConvertDecoded

dsio/csv.go, dsio/csv_test.go, dsio/dsio.go, dsio/dsio_test.go, dsio/xlsx.go, tabular/tabular.go, tabular/tabular_test.go
This one's been a long time coming. we use JSON Schema to describe the structure of a dataset body, which gives us lots of flexibility for defining shemas. For tabular data formats this if often _too_ much flexibility. Qri does as much work as possible to get schemas into a tabular shape by default, but we don't have much in the way of feedback when tabular structures get messed up or corrupted, or when we'd like to use flexible formats like JSON in a tabular context.
So, let's define a package `tabular` specifically for working with tabular data. I can see this package growing over time to include things more than just structure validation.
=> feat: tabular package specifically for working with tabular data structure

detect/detect.go, detect/detect_test.go, structure.go, structure_test.go, tabular/tabular_test.go
#222 uncovered a number of issues in the qri-io/qri codebase, including one case within `fsi.Init` where a CSV writer was relying on not having a tabular schema where one is needed.
fsi.Init is special, because the data being written to disk is coming from a pure go source, and we now need a schema to allocate a `dsio.CSVWriter`. This PR adds a function to infer a "machine only" schema for such a context, and a new method on dataset.Structure to help determine when this is needed.
=> feat: detect tabular schema from go types

dsio/csv.go, dsio/replacecr/replace_cr.go
Increased read buffer size to be on par with the json reader. Results in a significant throughput improvement for the save path.
=> perf(csv): increase read buffer size for csv reader

dataset.go, dataset_test.go, kind.go
The already-existing SignableBytes method produces a string that gets signed with each commit. In general form it's `commit.Timestamp` and `structure.Checksum` joined by a newline. The output of SignableBytes looks like
this:
```
2001-01-01T06:01:01Z
QmaqzQkPWZW9AY5BbkVqB4cup8tTs5w9tDyLwonpLWD7Dj
```
Two big problems with this approach:
* Calculating a checksum requires loading the contents of the entire byte slice
into memery. It's neither practical nor feasible to calculate checksums of
very large body files
* We're only signing a checksum for the _body_, making it possible to construct
a version that alters data outside the body without invalidating the signature
Solve both problems by introducing a new method SigningBytes and mark `SignableBytes` as deprecated. `SigningBytes` returns …
=> feat(SigningBytes): new SigningBytes includes all components

dsstats/stats.go, dsstats/stats_test.go
stats accumulator should be a write destination instead of a hard requirement of being the sole consumer of a reader
=> refactor(dsstats): adjust Accumlator to be a Writer

dataset.go, dataset_test.go, readme.go, readme_test.go, testdata/readmes/invalidJSON.json, testdata/readmes/readmeconfig1.json, testdata/readmes/readmeconfig2.json, testdata/readmes/readmeconfig3.json, transform.go, transform_test.go, viz.go, viz_test.go
I think we should start shifting the "dynamic" methods for working with datasets down into the dataset package itself. Most of this is defined in [`github.com/qri-io/qri/base/component`](https://github.com/qri-io/qri/blob/master/base/component/component.go).
We should start selectively pulling the the utilitarian methods that express datasets & components using dynamic types & interfaces down into the dataset package, but adding _lots_ of tests in the process. This PR is a start to that, adding a `PathMap` method to dataset, and "runtime comparison" method to components that are inlined at save time.
I'm not sure how to name this, but here's the general problem this method solves: 
you have two components that are in different states of persistence that need to be checked for equality. …
=> feat(FeildsEqual,PathMap): add utility methods for comparing datasets

transform.go, transform_test.go
closes #246 
Adds `Steps` field to `Transform` struct and adds `TransformSteps` struct.
Adjusts `transform.MarshalJSONObject`, `transform.Assign`, `transform.ShallowCompare`, & `transform.IsEmpty`.
Also adjusts each associated test to ensure the `Steps` field is being handled.
Also, changes `transform.SyntaxVersion` from `string` to `map[string]string` type, as per [this comment](https://github.com/qri-io/dataset/pull/247#issuecomment-762573306) by b5 below:
> Steps add the possibility of multiple syntaxes being mixed in the same transform, so we need to manage a map of "execution syntaxes" to their versions. The one solution would be to add a SyntaxVersions field of type map[string]string to the Transform struct, where each key is a unique syntax used in at least one step, and the value …
=> refactor(Transform): add `Step` field to cover step-based execution

dataset.go, dataset_test.go
In qri-io/qri land we talk about a cascade of values from refstring to dataset, where each structure is a superset of the structure before it:
* reference string: "b5/population@/ipfs/hash"
* dsref.Ref: { "username": "b5", "name": "population", "path": "/ipfs/hash" }
* dsref.VersionInfo: { "username": "b5", "name": "population", "path": "/ipfs/hash", "commitTitle": "added..." }
* dataset.Dataset: { /* complete dataset */ }
This lets us expand-to-suit depending on the needs of the operation. It also means that any field that can be represented in a smaller structure must be present in all others.
In a separate conversation we've been on a push to use _stable identifiers for dataset histories_, which have to be worked into _all_ of these structures to be effective. This commit adds an ID …
=> feat(dataset): add ID field to dataset.Dataset

dataset.go
Might make sense to expand this beyond just `dataset.BodyFile()`.
This was causing a bug in `startf`, where if this was there was no previous version of a dataset, `ds.get_body` would segfault. It was relying on `dataset.BodyFile()`, which, if there was no dataset, would segfault b/c of a nil pointer dereference.
Again, might be beneficial to expand this for all the `dataset` methods.
=> fix(`dataset.BodyFile`): if no dataset exists, return nil

dataset.go, detect/detect.go, detect/detect_test.go
and add a bunch of tests / fixes. There are a few spots in the qri codebase that will be much cleaner with this abstraction, and having it in dataset with these tests will help make behaviour more consistent.
The tests I've added make a few more assurances that detect.Structure is idempotent
=> feat(detect.Structure): move struture detection function down from qri

transform.go, transform_test.go
instead of concatenating arrays. This was creating a situation in qri where scripts were doubling their steps slice on each call to `preview.Create` (which uses Assign). My bad!
=> fix(transform): Assign() overwrites Steps field

compression/compression.go, compression/compression_test.go
properly interpret strings like 'gz' and 'zstd' as gzip & zstandard compression respectively
=> fix(compression): coerce various format strings while parsing

dsio/dsio.go, dsio/json.go, dsio/json_test.go
string parser is choking on complex escape sequences, fix by falling back to `encoding/json` package unmarshaler. This is slower, but works where our current approach fails.
@dustmop seeking your review on this. I'd love a follow up that makes this less bad
=> fix(dsio): handle JSON strings properly

dsio/csv_test.go, dsio/json.go, dsio/json_test.go, dsio/xlsx_test.go
Handle all json escape sequences using a byte-by-byte inspection. Also handle escaped hex codes, which are technically out of spec, but often sent in json data. This approach is significantly faster than previous methods.
This benchmark run shows that BenchmarkJSONReader runs approximately 2x as fast.
```
BEFORE
goos: darwin
goarch: amd64
pkg: github.com/qri-io/dataset/dsio
cpu: Intel(R) Core(TM) i7-4980HQ CPU @ 2.80GHz
BenchmarkCBORWriterArrays-8    	   10000	    117795 ns/op
BenchmarkCBORWriterObjects-8   	    6321	    192148 ns/op
BenchmarkCBORReader-8          	    2022	    583629 ns/op
BenchmarkCSVWriterArrays-8     	    2220	    525497 ns/op
BenchmarkCSVWriterObjects-8    	    2248	    526928 ns/op
BenchmarkCSVReader-8           	    1894	    620847 ns/op
BenchmarkJSONWriterArrays-8 …
```
=> fix(json): Unescape json strings using byte-by-byte inspection

stepfile/stepfile.go, stepfile/stepfile_test.go, stepfile/testdata/steps.json, stepfile/testdata/steps.txt
this'll let us read/write transform files broken into steps. Borrows from a "convention" I've seen in a few places, most recently in [Starlark's internal testing package](https://github.com/google/starlark-go/blob/master/internal/chunkedfile/chunkedfile.go).
We can expand this in the future in two ways:
1. `Read()` returns three arguments: the parsed steps, _a struct of line offsets_, and an error. This offset struct would let us print out errors for input files that say things like `error on line 34 (step 2, line 1): missing separator`
2. Support _front matter_ on each step like syntax, title, and description that correspond to fields on `dataset.TransformStep`. The challenge here is picking a syntax for the front matter.
One possible example of front matter in the future: just use …
=> feat(stepfile): stepfile reads and writes step flat files
